### ISSUE TITLE
CamillaDSP Release v0.4.0 and gui backend v0.4.1

### ISSUE THREAD

**Issue by Gt1ult** [Lykkedk/SuperPlayer#1]
Dear Lykkedk,

I am new in the world of RPI and room correction. I have installed picoreplayer and I really like it (before I used moode player).

I would like to learn more regarding room correction and buy a minidsp UMIK-1. But before to buy it I would like to be sure I can apply the room correction found with REW.

I saw the project CamillaDSP and HenrikEnquist give me the link of your project: SuperPlayer.

The guide is really well done, thank you so much for sharing with the community. Thank you so much for the detailed guide I found it very well done (I still have to do), not all of us are genius like you and HenrikEnquist!!

Before starting all the procedure to install CamillaDSP and SuperPlayer,I would ask you if it is compatible with CamillaDSP Release v0.4.0 and gui backend v0.4.1? Ad if it will be compatible with the new releases?

I really like picoreplayer but I do not have your skills (I am quite far), do you suggest to use another system like dietpi to make my life easier?  

Thank you so much again!!!

Kind Regards,
Francesco

**Comment by Lykkedk** [comment]
Hello Francesco.
Thank's for your'e very kind words ;-)

I was away for nearly two months with my diyaudio hobby, but i'am looking into this now.
I suggest that you follow the CamillaDSP thread over at diyaudio, and when we solve the issue, we can close this one.

Rgds; Jesper (lykkedk at diyaudio.com)

**Comment by Gt1ult** [comment]
Hi Jesper,

I am starting to follow the Camilla thread at diyaudio, but you guys are too forward for my skills ahahah.

What do you mean for "when we solve the issue, we can close this one". What issue?

Kind Regards,
Francesco

**Comment by Lykkedk** [comment]
Ohh... sorry i misunderstud this.

I see that the version 4 cannot run as it is on the SuperPlayer.
I suggest you start installing the version i use, and try to make that work.

We can allway's change the stuff on your'e Picoreplayer afterward's and install the version 4 when i have it working.
I will help you offcause.

Regarding the use of Picoreplayer, i think you should stuck with it, as it is really good at this.

Jesper.

**Comment by Gt1ult** [comment]
Thank you so much for your help, I really appreciate that!!!

I will stuck with Picoreplayer as you suggest, I really like it 👍 )!!

Today I was too curious to try before receiving the answer and I tried with the CamillaDSP 4.0 hahahahah. 

I have installed  CamillaDSP 3.1, now it is ok. Before when I reproduced files with a sample rate of 96 kHz the reproduction was very slow. Now it is ok. I had to reboot several time, as it stopped by itself. It is one hour that it is running now without any issue :).

Still I have to complete the full procedure but now I am on the right side. Now I can buy the miniDSP UMIK-1 :)!!

I am trying to understand if the sound is the same with the loop, maybe I am wrong but the music sounds a bit different to my hear.

Could you explain ALSA setting 160:4::1? I could not find any info in the forums, google  and in squeezelite how to. I have a Khandas Tone Board.

Thank you so much again.

All the best,
Francesco

**Comment by Lykkedk** [comment]
Hi Francesco.

You can see what the parameters mean in th PicorePlayer webinterface ;-)

Specify the ALSA params to open output device (-a)   less>

<b>:<p>:<f>:<m>:<d>

    b = buffer time in ms or size in bytes
    p = period count or size in bytes
    f = sample format (16|24|24_3|32)
    m = use mmap (0|1)
    d = opens ALSA twice (undocumented) i.e. ::::d


Jesper.

**Comment by Gt1ult** [comment]
Good afternoon Jesper,

As always thank you very much. Actually what I meant is how to set properly them, in fact I do not know how to find the correct values for the khadas tone board. However I used the same numbers found in your super guide and everything is working well. I just was wondering if there are better number for my settings or if leaving all the values empty is fine as well.

I am following you in diyaudio, thank you from my side and all audio community for your and HenrikEnquist hard work. A lot appreciated. I would like to help but unfortunately I am just at the start of this journey.   

All the best!!
Francesco

**Comment by Lykkedk** [comment]
I have created an upgrade to the p.t. newest camilla + camillaGui stuff... see my SuperPlayer v2
I am will close this now ;-)
