### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by Gt1ult** [Lykkedk/SuperPlayer#3]
Hi Jesper,

How do you doing? Hopefully everything is going well with you. 

I am ok and I bought the miniDSP UMIK-1 :). Still I have to learn how to use properly, however I found the first filter to apply :). I have tested the filter in windows with EqualizerAPO. Anforunatelly I m not sure how to apply the filter in SuperPlayer/CamillaDSP. I found the filter in REW and I exported the txt:
[20201008_Test6_individual max boost 9 - intervall max boost 6 .txt](https://github.com/Lykkedk/SuperPlayer/files/5349464/20201008_Test6_individual.max.boost.9.-.intervall.max.boost.6.txt)

Filter Settings file

Room EQ V5.19
Dated: 8-ott-2020 16.50.02

Notes:test6

Equaliser: Generic
Average 1
Filter  1: ON  PK       Fc    2380 Hz  Gain   7.2 dB  Q 1.005
Filter  2: ON  PK       Fc    5778 Hz  Gain  -5.0 dB  Q 1.000
Filter  3: ON  PK       Fc    1822 Hz  Gain  -3.7 dB  Q 1.000
Filter  4: ON  PK       Fc     396 Hz  Gain  -8.0 dB  Q 2.473
Filter  5: ON  PK       Fc     620 Hz  Gain  -3.3 dB  Q 1.000
Filter  6: ON  PK       Fc    20.0 Hz  Gain  -6.9 dB  Q 2.258
Filter  7: ON  PK       Fc    7323 Hz  Gain   3.0 dB  Q 1.356
Filter  8: ON  PK       Fc    26.4 Hz  Gain   9.0 dB  Q 4.212
Filter  9: ON  PK       Fc     432 Hz  Gain   9.0 dB  Q 5.000
Filter 10: ON  PK       Fc    1219 Hz  Gain   1.6 dB  Q 1.000
Filter 11: ON  PK       Fc     701 Hz  Gain   5.0 dB  Q 4.773
Filter 12: ON  PK       Fc     150 Hz  Gain -10.0 dB  Q 9.689
Filter 13: ON  PK       Fc     819 Hz  Gain  -4.5 dB  Q 5.000
Filter 14: ON  PK       Fc     289 Hz  Gain   4.1 dB  Q 5.000
Filter 15: ON  PK       Fc     630 Hz  Gain   3.0 dB  Q 5.000
Filter 16: ON  PK       Fc    3109 Hz  Gain   1.9 dB  Q 3.296
Filter 17: ON  PK       Fc     223 Hz  Gain  -2.2 dB  Q 5.000
Filter 18: ON  PK       Fc     183 Hz  Gain   4.5 dB  Q 12.366
Filter 19: ON  PK       Fc     162 Hz  Gain   4.8 dB  Q 25.933
Filter 20: ON  None   

Preamp: -6.3 dB

Could you help me to upload this filter? Thank you so much?

I would like to understand better the "Tweaks and finishing up" to test the difference with the filters. Could you help me in this as well?

As always all the best and many thanks.

Kind regards,
Francesco

**Comment by Lykkedk** [comment]
Hi Francesco

On the REW site [https://www.roomeqwizard.com/](url) and also on the rePhase [https://rephase.org/](url) there are some guides to get you going for a start.

The learning curve into DRC/DSP is rather steep, but sooner or later you will understand.

I suggest you start making some measurements with your'e mic, and create an EQ of this (Left + Right), then create a .bin filter in rePhase and apply this to CamillaDSP engine. I'am not the best guy to explain this, but i'am sure you can find or ask the quistions in the link i attached or in the camilladsp thread [https://www.diyaudio.com/forums/pc-based/349818-camilladsp-cross-platform-iir-fir-engine-crossovers-correction-etc.html](url)

Good luck... you will eventually success ;-)

Jesper.

**Comment by Lykkedk** [comment]
I have created an upgrade to the p.t. newest camilla + camillaGui stuff... see my SuperPlayer v2
I am hoping i can close this then ?

**Comment by Lykkedk** [comment]
Also save to close now i hope
